# rustfmt.toml

max_width = 120
tab_spaces = 2

# Removido, use `edition = "2015"` ou `edition = "2018"` no seu `Cargo.toml` para controlar o estilo de formatação.
# dense_formatting = false 



# Renomeado para `reorder_imports` e `group_imports` (sem `_`)
reorder_imports = true

# Removido, use o atributo `#[rustfmt::skip]` para pular a formatação em macros específicas.
# format_macro_matchers = true 

